openapi: 3.2.0
info:
  title: Versusgame Custom URLS API
  description: APIs for Versusgame Application
  version: '1.0'
  contact: {}
tags:
- name: custom-urls
paths:
  /v1/custom-urls/{url}:
    get:
      operationId: CustomUrlController_findByUrl
      parameters:
      - name: url
        required: true
        in: path
        schema:
          type: string
      responses:
        '200':
          description: Gets an customurl entry by url
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomUrl'
      tags:
      - custom-urls
  /v1/admin/custom-urls/{customUrlId}:
    patch:
      operationId: CustomUrlAdminController_update
      parameters:
      - name: customUrlId
        required: true
        in: path
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateCustomUrlDto'
      responses:
        '204':
          description: Updated CustomUrl
      security:
      - access-token: []
      tags:
      - custom-urls
    get:
      operationId: CustomUrlAdminController_byId
      parameters:
      - name: customUrlId
        required: true
        in: path
        schema:
          type: string
      - name: _expand
        required: false
        in: query
        schema:
          $ref: '#/components/schemas/CustomUrlExpand'
      - name: expand
        required: false
        in: query
        schema:
          type: array
          items:
            $ref: '#/components/schemas/CustomUrlExpand'
      responses:
        '200':
          description: Get CustomUrl
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomUrl'
      security:
      - access-token: []
      tags:
      - custom-urls
  /v1/admin/custom-urls:
    get:
      operationId: CustomUrlAdminController_list
      parameters:
      - name: _expand
        required: false
        in: query
        schema:
          $ref: '#/components/schemas/CustomUrlExpand'
      - name: expand
        required: false
        in: query
        schema:
          type: array
          items:
            $ref: '#/components/schemas/CustomUrlExpand'
      - name: search
        required: false
        in: query
        schema:
          $ref: '#/components/schemas/CustomUrlSearchFindAllDto2'
      - name: sort
        required: false
        in: query
        schema:
          $ref: '#/components/schemas/CustomUrlSortFindAllDto2'
      - name: limit
        required: false
        in: query
        schema:
          type: number
      - name: offset
        required: false
        in: query
        schema:
          type: number
      responses:
        '200':
          description: List of Custom Urls
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListCustomUrl'
      security:
      - access-token: []
      tags:
      - custom-urls
  /v1/creator/custom-urls:
    post:
      operationId: CustomUrlCreatorController_create
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCustomUrlDto'
      responses:
        '201':
          description: New CustomUrl
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomUrl'
      security:
      - access-token: []
      tags:
      - custom-urls
    patch:
      operationId: CustomUrlCreatorController_update
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateCustomUrlDto'
      responses:
        '204':
          description: Updated CustomUrl
      security:
      - access-token: []
      tags:
      - custom-urls
    get:
      operationId: CustomUrlCreatorController_get
      parameters:
      - name: _expand
        required: false
        in: query
        schema:
          $ref: '#/components/schemas/CustomUrlExpand'
      - name: expand
        required: false
        in: query
        schema:
          type: array
          items:
            $ref: '#/components/schemas/CustomUrlExpand'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomUrl'
      security:
      - access-token: []
      tags:
      - custom-urls
  /v1/creator/custom-urls/{Id}:
    delete:
      operationId: CustomUrlCreatorController_delete
      parameters: []
      responses:
        '204':
          description: Delete Custom-Url
      security:
      - access-token: []
      tags:
      - custom-urls
components:
  schemas:
    CustomUrlSortFindAllDto:
      type: object
      properties:
        url:
          allOf:
          - $ref: '#/components/schemas/SortMode'
        websiteTitle:
          allOf:
          - $ref: '#/components/schemas/SortMode'
    CustomUrlSearchFindAllDto2:
      type: object
      properties:
        search:
          $ref: '#/components/schemas/CustomUrlSearchFindAllDto'
    VideoUrls:
      type: object
      properties:
        hls:
          type: string
        mp4360:
          type: string
        mp4540:
          type: string
        mp4720:
          type: string
        poster:
          type: string
      required:
      - hls
      - mp4360
      - mp4540
      - mp4720
      - poster
    GameSet:
      type: object
      properties:
        id:
          type: string
        partnerId:
          type: string
        partner:
          $ref: '#/components/schemas/Creator'
        createdAt:
          format: date-time
          type: string
        updatedAt:
          format: date-time
          type: string
        startTime:
          format: date-time
          type: string
        endTime:
          format: date-time
          type: string
        deletedAt:
          format: date-time
          type: string
        games:
          type: array
          items:
            $ref: '#/components/schemas/Game'
      required:
      - id
      - partner
      - createdAt
      - updatedAt
      - startTime
      - endTime
      - deletedAt
      - games
    ListCustomUrl:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/CustomUrl'
        total:
          type: number
      required:
      - items
      - total
    Widget:
      type: object
      properties:
        type:
          allOf:
          - $ref: '#/components/schemas/WidgetTypes'
        id:
          type: string
        name:
          type: string
        creatorId:
          type: string
        creator:
          $ref: '#/components/schemas/Creator'
        playlistId:
          type: string
        playlist:
          $ref: '#/components/schemas/Playlist'
        deletedAt:
          format: date-time
          type: string
      required:
      - type
      - id
      - name
      - creatorId
      - creator
      - playlistId
      - playlist
      - deletedAt
    Playlist:
      type: object
      properties:
        language:
          allOf:
          - $ref: '#/components/schemas/Language'
        gameSet:
          $ref: '#/components/schemas/GameSet'
        id:
          type: string
        totalGames:
          type: number
        creatorId:
          type: string
        creator:
          $ref: '#/components/schemas/Creator'
        widgets:
          type: array
          items:
            $ref: '#/components/schemas/Widget'
        gamesOrder:
          type: array
          items:
            type: string
        games:
          type: array
          items:
            $ref: '#/components/schemas/Game'
        autofilledGames:
          type: array
          items:
            $ref: '#/components/schemas/Game'
        autofillCategories:
          type: array
          items:
            $ref: '#/components/schemas/Category'
        autofillCreators:
          type: array
          items:
            $ref: '#/components/schemas/Creator'
        autofillExcludedCreators:
          type: array
          items:
            $ref: '#/components/schemas/Creator'
        autofill:
          type: boolean
      required:
      - language
      - id
      - totalGames
      - creatorId
      - creator
      - widgets
      - games
      - autofilledGames
      - autofill
    CreateCustomUrlDto:
      type: object
      properties:
        widgetId:
          type: string
        url:
          type: string
        websiteTitle:
          type: string
        backgroundColor:
          type: string
        textColor:
          type: string
      required:
      - widgetId
      - url
      - websiteTitle
      - backgroundColor
      - textColor
    CustomUrlSortFindAllDto2:
      type: object
      properties:
        sort:
          $ref: '#/components/schemas/CustomUrlSortFindAllDto'
    GameType:
      type: string
      enum:
      - POLL
      - PREDICTION
      - INSTANT_POLL
      - TRIVIA
      - SURVEY
      - THIS_THAT
    CustomUrlSearchFindAllDto:
      type: object
      properties:
        creatorIds:
          type: array
          items:
            type: string
        url:
          type: string
        websiteTitle:
          type: string
    Game:
      type: object
      properties:
        audioUrl:
          type: string
        videoUrls:
          $ref: '#/components/schemas/VideoUrls'
        questionVideoUrls:
          $ref: '#/components/schemas/VideoUrls'
        landscapeVideoUrls:
          $ref: '#/components/schemas/VideoUrls'
        resultUrls:
          $ref: '#/components/schemas/VideoUrls'
        state:
          allOf:
          - $ref: '#/components/schemas/GameStates'
        language:
          allOf:
          - $ref: '#/components/schemas/Language'
        gameType:
          allOf:
          - $ref: '#/components/schemas/GameType'
        orientation:
          allOf:
          - $ref: '#/components/schemas/Orientation'
        correctAnswer:
          allOf:
          - $ref: '#/components/schemas/Side'
        id:
          type: string
        creatorId:
          type: string
        creator:
          $ref: '#/components/schemas/Creator'
        startTime:
          format: date-time
          type: string
        endTime:
          format: date-time
          type: string
        lastJoinTime:
          format: date-time
          type: string
        gameTitle:
          type: string
        sourceUrl:
          type: string
        sideA:
          type: string
        sideB:
          type: string
        videoAssetId:
          type: string
        questionVideoAssetId:
          type: string
        landscapeVideoAssetId:
          type: string
        audioAssetId:
          type: string
        resultAssetId:
          type: string
        text:
          type: string
        categoryId:
          type: string
        category:
          $ref: '#/components/schemas/Category'
        isAd:
          type: boolean
        isPrivate:
          type: boolean
        bingSearch:
          type: string
        bingSearchClaim:
          type: string
        metadata:
          type: object
        createdAt:
          format: date-time
          type: string
        updatedAt:
          format: date-time
          type: string
        version:
          type: number
        urls:
          type: array
          items:
            type: string
      required:
      - audioUrl
      - videoUrls
      - questionVideoUrls
      - landscapeVideoUrls
      - resultUrls
      - state
      - language
      - gameType
      - id
      - creatorId
      - creator
      - startTime
      - endTime
      - lastJoinTime
      - gameTitle
      - sourceUrl
      - sideA
      - sideB
      - text
      - categoryId
      - category
      - isAd
      - createdAt
      - updatedAt
      - version
    CustomUrl:
      type: object
      properties:
        creatorId:
          type: string
        creator:
          $ref: '#/components/schemas/Creator'
        widgetId:
          type: string
        widget:
          $ref: '#/components/schemas/Widget'
        url:
          type: string
        websiteTitle:
          type: string
        backgroundColor:
          type: string
        textColor:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
      required:
      - creatorId
      - creator
      - widgetId
      - widget
      - url
      - websiteTitle
      - backgroundColor
      - textColor
      - createdAt
      - updatedAt
    CustomUrlExpand:
      type: string
      enum:
      - creator
      - widget
    Language:
      type: string
      enum:
      - en-us
      - es-mx
    UpdateCustomUrlDto:
      type: object
      properties:
        widgetId:
          type: string
        url:
          type: string
        websiteTitle:
          type: string
        backgroundColor:
          type: string
        textColor:
          type: string
    Side:
      type: string
      enum:
      - A
      - B
    GameStates:
      type: string
      enum:
      - new
      - active
      - waiting_for_declaration
      - declaring_winner
      - winner_declared
      - changing_game_result
      - processing_payouts
      - ended
      - canceled
      - refunded
      - quarantined
    Creator:
      type: object
      properties:
        avatar:
          type: string
        id:
          type: string
        partnerName:
          type: string
        avatarAssetId:
          type: string
        profileColor:
          type: string
        userName:
          type: string
        createdAt:
          format: date-time
          type: string
        updatedAt:
          format: date-time
          type: string
      required:
      - avatar
      - id
      - partnerName
      - avatarAssetId
      - profileColor
      - userName
      - createdAt
      - updatedAt
    SortMode:
      type: string
      enum:
      - asc
      - desc
    Category:
      type: object
      properties:
        language:
          allOf:
          - $ref: '#/components/schemas/Language'
        id:
          type: string
        categoryName:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
        deletedAt:
          type: string
        sticker:
          type: string
        icon:
          type: string
      required:
      - language
      - id
      - categoryName
      - createdAt
      - updatedAt
      - deletedAt
    Orientation:
      type: string
      enum:
      - landscape
      - portrait
    WidgetTypes:
      type: string
      enum:
      - inline
      - expanding
      - mobile-expanding
      - docked
      - carousel
      - sidebar
      - playlist
  securitySchemes:
    access-token:
      scheme: bearer
      bearerFormat: JWT
      description: Enter the bearer token below (do not include 'Bearer')
      type: http
    x-api-key:
      type: apiKey
      in: header
      name: x-api-key
      description: API Key For External calls
