openapi: 3.2.0
info:
  title: Versusgame Health API
  description: APIs for Versusgame Application
  version: '1.0'
  contact: {}
tags:
- name: Health
paths:
  /healthcheck:
    get:
      operationId: HealthController_check
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: string
      tags:
      - Health
components:
  securitySchemes:
    access-token:
      scheme: bearer
      bearerFormat: JWT
      description: Enter the bearer token below (do not include 'Bearer')
      type: http
    x-api-key:
      type: apiKey
      in: header
      name: x-api-key
      description: API Key For External calls
